/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ArtistProfile = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'website' : IDL.Text,
});
export const Artwork = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'artist' : ArtistProfile,
  'price' : IDL.Nat,
});
export const PurchaseInquiry = IDL.Record({
  'id' : IDL.Nat,
  'artworkId' : IDL.Nat,
  'buyerEmail' : IDL.Text,
  'createdAt' : IDL.Int,
  'artwork' : Artwork,
  'message' : IDL.Text,
  'buyerName' : IDL.Text,
});
export const SubmissionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ArtworkSubmission = IDL.Record({
  'id' : IDL.Nat,
  'status' : SubmissionStatus,
  'submittedAt' : IDL.Int,
  'reviewedAt' : IDL.Opt(IDL.Int),
  'artwork' : Artwork,
  'artistPrincipal' : IDL.Principal,
  'artist' : ArtistProfile,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'avatar' : IDL.Opt(IDL.Text),
});
export const SubmissionResult = IDL.Record({ 'submissionId' : IDL.Nat });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveSubmission' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArtistProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createPurchaseInquiry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteArtwork' : IDL.Func([IDL.Nat], [], []),
  'editArtwork' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'getAllPurchaseInquiries' : IDL.Func(
      [],
      [IDL.Vec(PurchaseInquiry)],
      ['query'],
    ),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(ArtworkSubmission)], ['query']),
  'getArtistProfileByCaller' : IDL.Func([], [ArtistProfile], ['query']),
  'getArtistProfiles' : IDL.Func([], [IDL.Vec(ArtistProfile)], ['query']),
  'getArtworkById' : IDL.Func([IDL.Nat], [Artwork], ['query']),
  'getArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInquiriesByArtwork' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PurchaseInquiry)],
      ['query'],
    ),
  'getPurchaseInquiry' : IDL.Func([IDL.Nat], [PurchaseInquiry], ['query']),
  'getSubmissionsByCaller' : IDL.Func(
      [],
      [IDL.Vec(ArtworkSubmission)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectSubmission' : IDL.Func([IDL.Nat], [], []),
  'replaceDataset' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitArtwork' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [SubmissionResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ArtistProfile = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'website' : IDL.Text,
  });
  const Artwork = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'artist' : ArtistProfile,
    'price' : IDL.Nat,
  });
  const PurchaseInquiry = IDL.Record({
    'id' : IDL.Nat,
    'artworkId' : IDL.Nat,
    'buyerEmail' : IDL.Text,
    'createdAt' : IDL.Int,
    'artwork' : Artwork,
    'message' : IDL.Text,
    'buyerName' : IDL.Text,
  });
  const SubmissionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ArtworkSubmission = IDL.Record({
    'id' : IDL.Nat,
    'status' : SubmissionStatus,
    'submittedAt' : IDL.Int,
    'reviewedAt' : IDL.Opt(IDL.Int),
    'artwork' : Artwork,
    'artistPrincipal' : IDL.Principal,
    'artist' : ArtistProfile,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'avatar' : IDL.Opt(IDL.Text),
  });
  const SubmissionResult = IDL.Record({ 'submissionId' : IDL.Nat });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveSubmission' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArtistProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createPurchaseInquiry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteArtwork' : IDL.Func([IDL.Nat], [], []),
    'editArtwork' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'getAllPurchaseInquiries' : IDL.Func(
        [],
        [IDL.Vec(PurchaseInquiry)],
        ['query'],
      ),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(ArtworkSubmission)], ['query']),
    'getArtistProfileByCaller' : IDL.Func([], [ArtistProfile], ['query']),
    'getArtistProfiles' : IDL.Func([], [IDL.Vec(ArtistProfile)], ['query']),
    'getArtworkById' : IDL.Func([IDL.Nat], [Artwork], ['query']),
    'getArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInquiriesByArtwork' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PurchaseInquiry)],
        ['query'],
      ),
    'getPurchaseInquiry' : IDL.Func([IDL.Nat], [PurchaseInquiry], ['query']),
    'getSubmissionsByCaller' : IDL.Func(
        [],
        [IDL.Vec(ArtworkSubmission)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectSubmission' : IDL.Func([IDL.Nat], [], []),
    'replaceDataset' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitArtwork' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [SubmissionResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };