/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArtistProfile {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'createdAt' : bigint,
  'website' : string,
}
export interface Artwork {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'imageUrl' : string,
  'artist' : ArtistProfile,
  'price' : bigint,
}
export interface ArtworkSubmission {
  'id' : bigint,
  'status' : SubmissionStatus,
  'submittedAt' : bigint,
  'reviewedAt' : [] | [bigint],
  'artwork' : Artwork,
  'artistPrincipal' : Principal,
  'artist' : ArtistProfile,
}
export interface PurchaseInquiry {
  'id' : bigint,
  'artworkId' : bigint,
  'buyerEmail' : string,
  'createdAt' : bigint,
  'artwork' : Artwork,
  'message' : string,
  'buyerName' : string,
}
export interface SubmissionResult { 'submissionId' : bigint }
export type SubmissionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveSubmission' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArtistProfile' : ActorMethod<[string, string, string], undefined>,
  'createPurchaseInquiry' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
  'editArtwork' : ActorMethod<
    [bigint, string, string, string, bigint],
    undefined
  >,
  'getAllPurchaseInquiries' : ActorMethod<[], Array<PurchaseInquiry>>,
  'getAllSubmissions' : ActorMethod<[], Array<ArtworkSubmission>>,
  'getArtistProfileByCaller' : ActorMethod<[], ArtistProfile>,
  'getArtistProfiles' : ActorMethod<[], Array<ArtistProfile>>,
  'getArtworkById' : ActorMethod<[bigint], Artwork>,
  'getArtworks' : ActorMethod<[], Array<Artwork>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInquiriesByArtwork' : ActorMethod<[bigint], Array<PurchaseInquiry>>,
  'getPurchaseInquiry' : ActorMethod<[bigint], PurchaseInquiry>,
  'getSubmissionsByCaller' : ActorMethod<[], Array<ArtworkSubmission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectSubmission' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitArtwork' : ActorMethod<
    [string, string, string, bigint],
    SubmissionResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];